linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - revive
    - govet
    - unused
    - misspell
  disable:
    - errcheck

issues:
  exclude-rules:
    - linters:
        - revive
      text: "unused-parameter"

run:
  timeout: 3m
